// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

// import { TodoData } from "../../types/TodoData";
import ExtenedReducerAction from "./../reducerActions/reducerActions.extended";
// import extendedActions from "./../actions/action.extended";

/**
 * You may add here extending actionCreators for this features reducer
 * actionCreator: ([params]): ExtenedReducerAction => (
 * {
 *   type: extendedActions["[actionName]"],
 *   [payload]
 * }),
 * 
 */
export const extendedActionCreators = {}

type ActionCreator = { [key in string]: (...params: any[]) => ExtenedReducerAction };

const checkActionCreator: <T>(item: T & ActionCreator) => T = <T>(item: T & ActionCreator) => {
    return item;
};

export const todoActionCreatorsExtended = checkActionCreator(extendedActionCreators);

export default todoActionCreatorsExtended;
