// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { State } from "./state";

export const getTodoDefaultState = (): State => ({
    todos: [],
    categories: [],
    undefinableNumbers: null,
    undefinableNumber: null,
    currentData: null,
});

export default getTodoDefaultState;
