// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { TodoReducerActions as RAs } from "./reducerActions/reducerActions.main.generated";
import { State } from "./state";

export { todoReducer } from "./reducer/reducer.main.generated";
export { TODO_ACTIONS } from "./actions/actions.main.generated";
export { TODO_ACTIONS_EXTENDED } from "./actions/actions.extended";
export { TODO_ACTIONS_BASE } from "./actions/actions.base.generated";
export { todoActionCreators } from "./actionCreators/actionCreators.main.generated";
export * from "./ReducerContext.main.generated";

export { isTodoReducerActions } from "./reducerActions/reducerActions.main.generated";
export { isTodoReducerActionsExtended } from "./reducerActions/reducerActions.extended";
export { isTodoReducerActionsBase } from "./reducerActions/reducerActions.base.generated";

export { getTodoDefaultState } from "./defaultState.base.generated";
export { TodoStateProperties, TodoStatePropertiesEnum, isKeyofTodoState } from "./stateProperties.base.generated";

export type TodoReducerActions = RAs;
export type TodoState = State;
