// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import type { State } from "./state";

export const TodoStateProperties: { [key in keyof State]: key } = Object.freeze({
    todos: "todos",
    categories: "categories",
    undefinableNumbers: "undefinableNumbers",
    undefinableNumber: "undefinableNumber",
    currentData: "currentData",
});

export enum TodoStatePropertiesEnum {
    todos = "todos",
    categories = "categories",
    undefinableNumbers = "undefinableNumbers",
    undefinableNumber = "undefinableNumber",
    currentData = "currentData",
}

export function isKeyofTodoState(propertyName: any): propertyName is keyof State {
    return (
        typeof propertyName === "string" ||
        typeof propertyName === "number" ||
        typeof propertyName === "symbol"
        ) &&
        (
            propertyName === "todos" ||
            propertyName === "categories" ||
            propertyName === "undefinableNumbers" ||
            propertyName === "undefinableNumber" ||
            propertyName === "currentData"
        )
}
