// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { State } from "./../state";
import { getTodoDefaultState } from "./../defaultState.base.generated";
import { TODO_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
import { TodoReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const todoReducerBase = (state: State = getTodoDefaultState(), action: TodoReducerActionsBase): State => {
    switch (action.type) {
        case actions.TODO_SET_TODOS:
            return {
                ...state,
                todos: action.next,
            };
        case actions.TODO_SET_CATEGORIES:
            return {
                ...state,
                categories: action.next,
            };
        case actions.TODO_SET_UNDEFINABLE_NUMBERS:
            return {
                ...state,
                undefinableNumbers: action.next,
            };
        case actions.TODO_SET_UNDEFINABLE_NUMBER:
            return {
                ...state,
                undefinableNumber: action.next,
            };
        case actions.TODO_SET_CURRENT_DATA:
            return {
                ...state,
                currentData: action.next,
            };

    // cases for manipulating property arrays
        case actions.TODO_TODOS_ADD:
            return {
                ...state,
                todos: [...state.todos, action.next],
            };
        case actions.TODO_TODOS_UPDATE:
            const { todos : todosToBeUpdated } = state;
            return {
                ...state,
                todos:
                    todosToBeUpdated.map(item => item === action.next.oldItem ? action.next.nextItem : item),
            };
        case actions.TODO_TODOS_REMOVE:
            const { todos : todosOld } = state;
            return {
                ...state,
                todos:
                    todosOld.filter(item => item !== action.next),
            };
        case actions.TODO_CATEGORIES_ADD:
            return {
                ...state,
                categories: [...state.categories, action.next],
            };
        case actions.TODO_CATEGORIES_UPDATE:
            const { categories : categoriesToBeUpdated } = state;
            return {
                ...state,
                categories:
                    categoriesToBeUpdated.map(item => item === action.next.oldItem ? action.next.nextItem : item),
            };
        case actions.TODO_CATEGORIES_REMOVE:
            const { categories : categoriesOld } = state;
            return {
                ...state,
                categories:
                    categoriesOld.filter(item => item !== action.next),
            };
        case actions.TODO_UNDEFINABLE_NUMBERS_ADD:
            return {
                ...state,
                undefinableNumbers: [...(state.undefinableNumbers || []), action.next],
            };
        case actions.TODO_UNDEFINABLE_NUMBERS_UPDATE:
            const { undefinableNumbers : undefinableNumbersToBeUpdated } = state;
            return {
                ...state,
                undefinableNumbers:
                    undefinableNumbersToBeUpdated && undefinableNumbersToBeUpdated.length > 0 ?
                        undefinableNumbersToBeUpdated.map(item => item === action.next.oldItem ? action.next.nextItem : item) :
                        undefinableNumbersToBeUpdated,
            };
        case actions.TODO_UNDEFINABLE_NUMBERS_REMOVE:
            const { undefinableNumbers : undefinableNumbersOld } = state;
            return {
                ...state,
                undefinableNumbers: 
                    undefinableNumbersOld && undefinableNumbersOld.length > 0 ?
                        undefinableNumbersOld.filter(item => item !== action.next) :
                        undefinableNumbersOld,
            };
        default:
            return state;
    }
};

export default todoReducerBase;
