// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { State } from "./../state";
import { getTodoDefaultState } from "./../defaultState.base.generated";
import { todoReducerBase } from "./reducer.base.generated";
import { todoReducerExtended } from "./reducer.extended";
import { isTodoReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";
import { isTodoReducerActions } from "./../reducerActions/reducerActions.main.generated";

export const todoReducer = (state: State = getTodoDefaultState(), action: any): State => {
    // Note: Generator may be extended to inversify this order => Just talk to me ;)
    // return todoReducerExtended((isTodoReducerActionsBase(action) ? todoReducerBase(state, action) : state), action);

    if (!isTodoReducerActions(action)) {
        return state;
    }

    return (isTodoReducerActionsBase(action) ? todoReducerBase(todoReducerExtended(state, action), action) : todoReducerExtended(state, action));
};

export default todoReducer;
