// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).

import { State } from "./../state";
import { getTodoDefaultState } from "./../defaultState.base.generated";
import { TodoReducerActions } from "./../reducerActions/reducerActions.main.generated";

// import { type TodoData } from "../../types/TodoData";
// import { type TodoCategory } from "../../types/TodoCategory";

// import { TODO_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";
// import { TODO_ACTIONS_EXTENDED as actions } from "./../actions/actions.extended";

// Uncomment for some typechecking:
// import { isTodoReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { isTodoReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";

export const todoReducerExtended = (state: State = getTodoDefaultState(), action: TodoReducerActions): State => {
    switch (action.type) {
        //         case actions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //            };
        //         case extendedActions["[actionName]"]:
        //             return {
        //                 ...state,
        //                 // [action payload]
        //              };
        default:
            return state;
    }
};

export default todoReducerExtended;
