// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

export enum TODO_ACTIONS_EXTENDED {
// e.g. SET_IS_LOGGED_IN_EXT = "SET_IS_LOGGED_IN_EXT",

}

export default TODO_ACTIONS_EXTENDED