// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

import { State } from "./../state";
import getDefaultState from "./../defaultState.base.generated";
// import extendedActions from "./../actions/action.extended";
// import actions from "./../actions/action.base.generated";
import TodoReducerActions from "./../reducerActions/reducerActions.main.generated";
    
// Uncomment for some typechecking:
// import { isTodoReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";
// import { isTodoReducerActionsExtended } from "./../reducerActions/reducerActions.extended";

/**
 * You may add here extending reducer behaviors for this features reducer
 */        
const todoReducerExtended = (state: State = getDefaultState(), action: TodoReducerActions ): State => {
    switch (action.type) {
//         case actions["[actionName]"]:
//             return {
//                 ...state, 
//                 // [action payload]
//            };  
//         case extendedActions["[actionName]"]:
//             return {
//                 ...state, 
//                 // [action payload]
//              };  
        default:
            return state; 
    }
};

export default todoReducerExtended;
