// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { TODO_ACTIONS_BASE } from "./actions.base.generated";
import { TODO_ACTIONS_EXTENDED } from "./actions.extended";

export const TODO_ACTIONS = { ...TODO_ACTIONS_BASE, ...TODO_ACTIONS_EXTENDED };

export default TODO_ACTIONS;
