// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).

export enum TODO_ACTIONS_EXTENDED {
    // e.g. ADD_LOADING_HANDLE = "ADD_LOADING_HANDLE",
}

export default TODO_ACTIONS_EXTENDED;
