// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { type TodoData } from "../../types/TodoData";
import { type TodoCategory } from "../../types/TodoCategory";
import { TODO_ACTIONS_BASE as actions } from "./../actions/actions.base.generated";

export type TodoReducerActionsBase = {
    type: actions;
    isBubbled?: boolean;
    } & (
    | {
        type: actions.TODO_SET_TODOS;
        next: TodoData[];
    }
    | {
        type: actions.TODO_SET_CATEGORIES;
        next: TodoCategory[];
    }
    | {
        type: actions.TODO_SET_UNDEFINABLE_NUMBERS;
        next: number[] | null;
    }
    | {
        type: actions.TODO_SET_UNDEFINABLE_NUMBER;
        next: number | null;
    }
    | {
        type: actions.TODO_SET_CURRENT_DATA;
        next: TodoData | null;
    }

    // reducer actions for manipulating arrays inside state
    | {
        type: actions.TODO_TODOS_ADD;
        next: TodoData;
    }
    | {
        type: actions.TODO_TODOS_UPDATE;
        // we will stick with "next" here, to make things easier, when not talking to duck-typing based languages/apps in the future
        next: {
            oldItem: TodoData;
            nextItem: TodoData;
        }
    }
    | {
        type: actions.TODO_TODOS_REMOVE;
        next: TodoData;
    }
    | {
        type: actions.TODO_CATEGORIES_ADD;
        next: TodoCategory;
    }
    | {
        type: actions.TODO_CATEGORIES_UPDATE;
        // we will stick with "next" here, to make things easier, when not talking to duck-typing based languages/apps in the future
        next: {
            oldItem: TodoCategory;
            nextItem: TodoCategory;
        }
    }
    | {
        type: actions.TODO_CATEGORIES_REMOVE;
        next: TodoCategory;
    }
    | {
        type: actions.TODO_UNDEFINABLE_NUMBERS_ADD;
        next: number;
    }
    | {
        type: actions.TODO_UNDEFINABLE_NUMBERS_UPDATE;
        // we will stick with "next" here, to make things easier, when not talking to duck-typing based languages/apps in the future
        next: {
            oldItem: number;
            nextItem: number;
        }
    }
    | {
        type: actions.TODO_UNDEFINABLE_NUMBERS_REMOVE;
        next: number;
    }
);

export const isTodoReducerActionsBase = (
    item: any
): item is TodoReducerActionsBase => {
    if (!item) {
        return false;
    }
    if (typeof item === "object") {
        const { type } = item;

        return (
            typeof type === "string" &&
            Object.hasOwnProperty.call(actions, type)
        );
    }
    return false;
};

export default TodoReducerActionsBase;
