// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { TodoReducerActionsBase, isTodoReducerActionsBase } from "./reducerActions.base.generated";
import { TodoReducerActionsExtended, isTodoReducerActionsExtended } from "./reducerActions.extended";

export type TodoReducerActions = TodoReducerActionsBase | TodoReducerActionsExtended;

export const isTodoReducerActions = (item: any): item is TodoReducerActions => {
    return isTodoReducerActionsBase(item) || isTodoReducerActionsExtended(item);
}

export default TodoReducerActions;
