// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).

import { TODO_ACTIONS_EXTENDED as extendedActions } from "./../actions/actions.extended";

/**
 * You may add here extending reducer actions for this features reducer
 */
export type TodoReducerActionsExtended = {
    type: extendedActions;
    isBubbled?: boolean;
} & {
    // replace by following template for every extendedActions
    //    | {
    //        type: extendedActions["[action name]"];
    //        /* [additional payload like : next:  boolean;]*/
    //    }
};

export const isTodoReducerActionsExtended = (
    item: unknown
): item is TodoReducerActionsExtended => {
    if (!item) {
        return false;
    }
    if (typeof item === "object" && item !== null && "type" in item) {
        const { type } = item;

        return (
            typeof type === "string" &&
            Object.hasOwnProperty.call(extendedActions, type)
        );
    }
    return false;
};

