// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { type TodoData } from "../../types/TodoData";
import { type TodoCategory } from "../../types/TodoCategory";
import { TodoReducerActionsBase as ReducerActions } from "./../reducerActions/reducerActions.base.generated";
import { TODO_ACTIONS as actions } from "./../actions/actions.main.generated";

export const todoActionCreatorsBase = {
    setTodos: (nextTodos: TodoData[]): ReducerActions => ({
        type: actions.TODO_SET_TODOS,
        next: nextTodos,
    }),
    setCategories: (nextCategories: TodoCategory[]): ReducerActions => ({
        type: actions.TODO_SET_CATEGORIES,
        next: nextCategories,
    }),
    setUndefinableNumbers: (nextUndefinableNumbers: number[] | null): ReducerActions => ({
        type: actions.TODO_SET_UNDEFINABLE_NUMBERS,
        next: nextUndefinableNumbers,
    }),
    setUndefinableNumber: (nextUndefinableNumber: number | null): ReducerActions => ({
        type: actions.TODO_SET_UNDEFINABLE_NUMBER,
        next: nextUndefinableNumber,
    }),
    setCurrentData: (nextCurrentData: TodoData | null): ReducerActions => ({
        type: actions.TODO_SET_CURRENT_DATA,
        next: nextCurrentData,
    }),

    // Action Creators for manipulating arrays inside state
    todosAddItem: (item: TodoData): ReducerActions => ({
        type: actions.TODO_TODOS_ADD,
        next: item,
    }),
    todosUpdateItem: (oldItem: TodoData, nextItem: TodoData): ReducerActions => ({
        type: actions.TODO_TODOS_UPDATE,
        next: {
            oldItem,
            nextItem,
        }
    }),
    todosRemoveItem: (item: TodoData): ReducerActions => ({
        type: actions.TODO_TODOS_REMOVE,
        next: item,
    }),
    categoriesAddItem: (item: TodoCategory): ReducerActions => ({
        type: actions.TODO_CATEGORIES_ADD,
        next: item,
    }),
    categoriesUpdateItem: (oldItem: TodoCategory, nextItem: TodoCategory): ReducerActions => ({
        type: actions.TODO_CATEGORIES_UPDATE,
        next: {
            oldItem,
            nextItem,
        }
    }),
    categoriesRemoveItem: (item: TodoCategory): ReducerActions => ({
        type: actions.TODO_CATEGORIES_REMOVE,
        next: item,
    }),
    undefinableNumbersAddItem: (item: number): ReducerActions => ({
        type: actions.TODO_UNDEFINABLE_NUMBERS_ADD,
        next: item,
    }),
    undefinableNumbersUpdateItem: (oldItem: number, nextItem: number): ReducerActions => ({
        type: actions.TODO_UNDEFINABLE_NUMBERS_UPDATE,
        next: {
            oldItem,
            nextItem,
        }
    }),
    undefinableNumbersRemoveItem: (item: number): ReducerActions => ({
        type: actions.TODO_UNDEFINABLE_NUMBERS_REMOVE,
        next: item,
    }),
};

export default todoActionCreatorsBase;
