// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021 / 2022 / 2023 (times runs ... ;) ).

// Uncomment imports if you need to ;)
// import { type TodoData } from "../../types/TodoData";
// import { type TodoCategory } from "../../types/TodoCategory";

import { type TodoReducerActionsExtended } from "./../reducerActions/reducerActions.extended";
// import { TODO_ACTIONS_EXTENDED } from "./../actions/actions.extended";

/**
 * You may add here extending actionCreators for this features reducer
 * actionCreator: ([params]): ExtenedReducerAction => (
 * {
 *   type: TODO_ACTIONS_EXTENDED["[actionName]"],
 *   [payload]
 * }),
 */
const extendedActionCreators = {
    // Add functions like
    // addLoadingHandle: (handleToAdd: symbol) => {
    //    return {
    //        type: TODO_ACTIONS_EXTENDED.ADD_LOADING_HANDLE,
    //        handle: handleToAdd
    //        };
    //    },
}

// Start: This is just for typechecking, so that you can utilize the awesomeness of Typescript
type ActionCreator = { [key in string]: (...params: unknown[]) => TodoReducerActionsExtended };

const checkActionCreator: <T>(item: T & ActionCreator) => T = <T>(item: T & ActionCreator) => {
    return item;
};
// End (The function above will be used to create the named export below)

export const todoActionCreatorsExtended = checkActionCreator(extendedActionCreators);

export default todoActionCreatorsExtended;
