// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020 / 2021.

// import { TodoData } from "../../types/TodoData";
import extenededActions from "./../actions/action.extended";
        
/**
 * You may add here extending reducer actions for this features reducer
 */        
export type TodoReducerActionsExtended = { type: extenededActions; isBubbled?: boolean } & (
    | {} // replace by following template for every extenededActions
//    | {
//        type: extenededActions["[action name]"];
//        /* [additional payload like : next:  boolean;]*/
//    }
);

export const isTodoReducerActionsExtended = (item: any): item is TodoReducerActionsExtended => {
    if (!item) { return false; }
    if (typeof item === "object") {
        const { type } = item;

        return typeof type === "string" && extenededActions.hasOwnProperty(type);
    }
    return false;
}

export default TodoReducerActionsExtended;
