# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Lets try an action

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on:
  workflow_dispatch:
    inputs:
      loglevel:
        default: "verbose"
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd lib && npm ci
    - run: cd lib && npm run build


#    - run: npm test
