# This is a basic workflow that is manually triggered
name: Create Publishable Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd lib && npm ci
    - run: cd lib && npm run build
#    - run: npm test
    
    - name: create ZIP archive
      shell: bash
      run: zip -r "archive-node-${{ matrix.node-version }}.zip" "lib/*"

    - name: Archive code 
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: "archive-node-${{ matrix.node-version }}.zip"
