# This is a basic workflow that is manually triggered
name: Create Publishable Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  readver:
    # uses: derfrodok/reducer-gen/.github/workflows/readPackageVersion.yml@main
    uses: ./.github/workflows/templateReadPackageVersion.yml
    with:
      packageName: "@derfrodo/reducer-gen"
    secrets:
      testsecret: demosecret

  build:
    name: "Test and Build bundle (${{ matrix.node-version }})"
    runs-on: ubuntu-latest
    needs: readver
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: perform installation (npm ci)
      shell: bash
      run: cd lib && npm ci
    
    - name: perform unittests
      shell: bash
      run: |
        cd lib
        npm test
    
    - name: build bundle (npm ci)
      shell: bash
      run: cd lib && npm run build
      
    - name: prepare package for publishing
      shell: bash
      run: |
        cd lib
        npm run prepareForPublish

    - name: Archive code 
      uses: actions/upload-artifact@v2
      with:
        name: reducer-gen-${{ needs.readver.outputs.packageVersion }}-node-${{ matrix.node-version }}-run-${{ github.run_id }}
        path: "lib"