# This is a basic workflow that is manually triggered
name: Create Publishable Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  nodeVersion: 16.x
  packageName: "@derfrodo/reducer-gen"
  artefactName: "derfrodo_reducer-gen"

jobs:

  readver:
    # uses: derfrodok/reducer-gen/.github/workflows/readPackageVersion.yml@main
    uses: ./.github/workflows/templateReadPackageVersion.yml
    with:
      packageName: "@derfrodo/reducer-gen"
    secrets:
      testsecret: demosecret

  prepare: 
    runs-on: ubuntu-latest
    name: "Prepare build settings"
    needs: readver
    outputs:
      packageVersion: ${{ needs.readver.outputs.packageVersion  }}
      # artefactName: ${{ env.artefactName }}-${{ needs.readver.outputs.packageVersion }}-run-${{ github.run_id }}
    steps:
    - name: Info
      run: |
        echo "Preparing Build for package ${{ needs.readver.outputs.packageVersion  }}"

  build:
    needs: 
    - prepare
    uses: ./.github/workflows/templateCreateBundle.yml
    with:
      # artefactName: ${{ needs.prepare.outputs.artefactName }}
      packageVersion: ${{ needs.prepare.outputs.packageVersion }}
      nodeVersions: "[\"14.x\", \"16.x\"]"
      include: "[]"
      # include: "[{\"nodeVersion\":\"14.x\", \"artefactName\":\"artefact-${{ needs.prepare.outputs.packageVersion }}-14.x-run-${{ github.run_id }}\"}]"
      
