# This is a basic workflow that is manually triggered
name: Create Publishable Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: perform installation (npm ci)
      shell: bash
      run: cd lib && npm ci
    
    - name: perform unittests
      shell: bash
      run: |
        cd lib
        npm test
    
    - name: build bundle (npm ci)
      shell: bash
      run: cd lib && npm run build
      
    - name: prepare package for publishing
      shell: bash
      run: |
        cd lib
        npm run prepareForPublish

    - name: Archive code 
      uses: actions/upload-artifact@v2
      with:
        name: code-node-${{ matrix.node-version }}
        path: "lib/*"
        
#    - name: create ZIP archive
#      shell: bash
#      run: |
#        cd lib
#        zip -r "../archive-node-${{ matrix.node-version }}.zip" "."

#    - name: Archive code 
#      uses: actions/upload-artifact@v2
#      with:
#        name: code-node-${{ matrix.node-version }}
#        path: "archive-node-${{ matrix.node-version }}.zip"
